# Generated by Django 4.2.5 on 2024-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0004_alter_comment_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created", "posted_by"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="posted_by",
            field=models.CharField(default="pinu", max_length=100),
            preserve_default=False,
        ),
    ]
