# Generated by Django 4.2.5 on 2024-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, default="images/avatar.png", upload_to="users/%Y/%m/%d"
            ),
        ),
    ]
